BOARD_TAG    = uno
MONITOR_PORT = /dev/tty.usbserial-A702ZNO6
ARDUINO_SKETCHBOOK = /Users/jschulz/Documents/Arduino/
ARDUINO_LIBS = Logging RFM69 SPI SPIFlash 
MONITOR_BAUDRATE = 115200
include /Users/jschulz/src/Arduino-Makefile/arduino-mk/Arduino.mk
