BOARD_TAG    = uno
MONITOR_PORT = /dev/tty.usbserial-A702ZNO6
#MONITOR_PORT = /dev/cu.usbserial-DA00EIRF

ARDUINO_SKETCHBOOK = /Users/jschulz/Documents/Arduino/
ARDUINO_LIBS = RFM69 SPI TDFBO Low-Power
MONITOR_BAUDRATE = 115200
include /Users/jschulz/src/Arduino-Makefile/arduino-mk/Arduino.mk
